name: Deploy DOR Metagraph Monitor - Mainnet

on:
  push:
    branches:
      - "deploy/dor-metagraph-mainnet"
jobs:
  deploy-mainnet-dor-metagraph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy DOR Metagraph Monitor - Mainnet
        uses: "./.github/templates/deploy"
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DOR }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DOR }}
          AWS_REGION: ${{ secrets.AWS_REGION_DOR}}
          AWS_LAMBDA_FUNCTION_NAME: MainnetMetagraphMonitor